global using System;
global using System.Collections.Generic;
global using System.Text;
global using Microsoft.Playwright;
global using static Microsoft.Playwright.Assertions;
global using BaseProject.Base;
global using BaseProject.Extensions;
global using Allure.Net.Commons;
global using BaseProject.AllureHelpers;
global using BaseProject.Helpers;
